language: python
python:
  - "3.6"
install:
  - pip install pycodestyle
  - pip install -r requirements.txt
script:
  - pycodestyle aerende
  - pycodestyle tests
  - python -m unittest -v
notifications:
  email: false
